a = ("hello I love programming!")
print(a[0])
print(a[13])
print(a[-2])

print("\n\n") 

a = ("I love programming!")
print(a[10:14])
print(a[2:])
print(a[0::2])
print(a[::-1]) #reverse ==== !gnimmargorp evol I
print("\n\n")
a = ("NEPAL")
print(a[0:1])
print(a[0:2])
print(a[0:3])
print(a[0:4])
print(a[0:5])
print("\n\n")
print(a[0:5])
print( " "*1 + a[1:5])
print(" "*2 + a[2:5])
print(" " *3 + a[3:5])
print(" " *4 + a[4:5])
print("\n\n")
a = ("KATHMANDU")
print(a[0:9])
print( " "*1 + a[1:8])
print(" "*2 + a[2:7])
print(" " *3 + a[3:6])
print(" " *4 + a[4:5])
print( " "*5 + a[5:4])
